server.port=9999

spring.application.name=gateway-api

############################################################
# Spring Cloud Gateway Routes
############################################################

#http://localhost:9999/api/data/execute
spring.cloud.gateway.routes[0].id=data-api
#spring.cloud.gateway.routes[0].uri=http://localhost:9995
#for docker
spring.cloud.gateway.routes[0].uri=http://data-api:9995
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/data/**

spring.cloud.gateway.routes[1].id=definition-api
#spring.cloud.gateway.routes[1].uri=http://localhost:9996
spring.cloud.gateway.routes[1].uri=http://definition-api:9996
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/**

############################################################
# Actuator
############################################################

management.endpoints.web.exposure.include=health,info,gateway

############################################################
# Logging
############################################################

logging.level.org.springframework.cloud.gateway=DEBUG

############################################################
# OAuth2 Resource Server
############################################################

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9001/realms/platform
#for docker
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/platform


logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.server.resource=TRACE
