services:

  gateway-api:
    build:
      context: .
      dockerfile: gateway-api/Dockerfile
    container_name: gateway-api
    ports:
      - "9999:9999"
    depends_on:
      - data-api
      - definition-api
      - user-access-api

  data-api:
    build:
      context: .
      dockerfile: data-api/Dockerfile
    container_name: data-api
    ports:
      - "9995:9995"

  definition-api:
    build:
      context: .
      dockerfile: definition-api/Dockerfile
    container_name: definition-api
    ports:
      - "9996:9996"

  user-access-api:
    build:
      context: .
      dockerfile: user-access-api/Dockerfile
    container_name: user-access-api
    ports:
      - "9997:9997"
